config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :lightning_talks
  resources :users
  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/lightning_talk.rb
class LightningTalk < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  
  validates :email, presence: true, uniqueness: true
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def create
  end
  
end

app/controllers/lightning_talks_controller.rb
class LightningTalksController < ApplicationController

  def index
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:message] = 'You successfully signed up!'
      redirect_to lightning_talks_path
    else
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<h1>Sign In, ready for your next Lightning Talk?</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LightningTalkApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lightning_talks/index.html.erb
<%= flash[:message] %>

app/views/welcome/index.html.erb
<%= link_to "Sign In", signin_path %>
<%= link_to "Sign Up", signup_path %>